services:
  - type: web
    name: warrior-dojo
    env: docker
    plan: free
    repo: https://github.com/WISH-CODES/warrior-dojo
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
